# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 819968f7a16188a8496c7e3e0427e02b738a1e09f08ac1a7c430986fc9fde369bbae1faeb53780baa21cf9b0f8f00032e8e19993eaa8489068fa252564c19529

test:
  secret_key_base: 8c6a3aa75e6b346d43d0da39b78ecf321d19cb97e2ad36956ddc6bce45ee9559c52cea310dcd62291a46f75c3f726a61cbf859a68c7fdb9a3386eb2c93c424dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
